apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ocr-model-metrics
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ocr-model
  namespaceSelector:
    matchNames:
    - ocr-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
