apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocr-gateway.fullname" . }}
  labels:
    {{- include "ocr-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ocr-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ocr-gateway.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ocr-gateway.fullname" . }}-sa
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ include "ocr-gateway.fullname" . }}-config
          - secretRef:
              name: {{ include "ocr-gateway.fullname" . }}-secret
          livenessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
