apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocr-gateway.fullname" . }}-secret
  labels:
    {{- include "ocr-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ "ocr-api-key-12345" | b64enc | quote }}
  db-password: {{ "secure-password-123" | b64enc | quote }}
