apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ocr-project
  namespace: argocd
spec:
  description: OCR Microservices Project
  sourceRepos:
  - https://github.com/KavinduGeesara/ocr-microservices.git
  destinations:
  - namespace: ocr-app
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: ''
    kind: Service
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: ServiceAccount
  - group: apps
    kind: Deployment
  - group: apps
    kind: ReplicaSet
  - group: ''
    kind: Pod
  - group: monitoring.coreos.com
    kind: ServiceMonitor
  # ADD THESE TWO LINES TO FIX THE RBAC ISSUE:
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
