apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ocr-model.fullname" . }}-role
  labels:
    {{- include "ocr-model.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
