apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocr-model.fullname" . }}
  labels:
    {{- include "ocr-model.labels" . | nindent 4 }}
    app.kubernetes.io/name: ocr-model
    release: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ocr-model.selectorLabels" . | nindent 4 }}
